[build-system]
requires = ["setuptools>=61.0", "appdirs"]
build-backend = "setuptools.build_meta"
[project]
name = "freva-rest"
description = "RestAPI the free evaluation system, freva"
authors = [{name = "DKRZ, Clint", email = "freva@dkrz.de"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
               "Development Status :: 3 - Alpha",
               "Environment :: Console",
               "Intended Audience :: Developers",
               "Intended Audience :: Science/Research",
               "License :: OSI Approved :: BSD License",
               "Operating System :: POSIX :: Linux",
               "Programming Language :: Python :: 3",
]
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = [
"aiohttp",
"fastapi",
"typer",
"uvicorn",
"python-dotenv",
"python-dateutil",
"tomli",
"rich",
"motor",
"requests",
]
[project.scripts]
freva-rest-server = "freva_rest.cli:cli"
[project.urls]
Documentation = "https://freva-clint.github.io/databrowserAPI"
Issues = "https://github.com/FREVA-CLINT/databrowserAPI/issues"
Source = "https://github.com/FREVA-CLINT/databrowserAPI/"

[project.optional-dependencies]
dev = ["tox"]

[tool.setuptools.package-data]
freva_rest = ["*.toml"]
[tool.distutils.bdist_wheel]
universal = true
[tool.setuptools.dynamic]
version = {attr = "freva_rest.__version__"}
