version: "3.9"
services:
  solr:
    image: solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./config/solr/synonyms.txt:/opt/solr/synonyms.txt:ro
      - ./create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: search_stats
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db:rw
