version: "3.9"
services:
  solr:
    image: solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./config/solr/synonyms.txt:/opt/solr/synonyms.txt:ro
      - ./create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
