version: "3.9"
services:
  solr:
    image: solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./config/solr/synonyms.txt:/opt/solr/synonyms.txt:ro
      - ./create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: redis
      REDIS_PASSWORD: secret
      REDIS_LOGLEVEL: debug
      REDIS_SSL_CERTFILE: /certs/client-cert.pem
      REDIS_SSL_KEYFILE: /certs/client-key.pem
    volumes:
      - ./redis-cmd.sh:/usr/local/bin/redis-cmd
      - ./certs:/certs
    command: /usr/local/bin/redis-cmd
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      JAVA_OPTS_APPEND: "-Djava.net.preferIPv4Stack=true"
    volumes:
      - ./certs:/certs
    ports:
      - "8080:8080"
      - "8443:8443"
    command: start --features=token-exchange

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: search_stats
    ports:
      - "27017:27017"
